---
- name: Install go
  dnf:
    name: golang-go
    state: present
  tags: 
  - ingo
  - never

- name: Remove go
  dnf:
    name: golang-go
    state: absent
  tags: 
  - ungo
  - never

- name: Install git
  dnf:
    name: git-all
    state: present
  tags:
  - ingit
  - never

- name: Remove git
  dnf:
    name: git-all
    state: absent
  tags:
  - ungit
  - never

- name: Remove Docker
  dnf:
    name: "{{item}}"
    state: absent
    update_cache: yes
  loop:
     - docker-ce
     - docker-ce-cli
     - containerd.io
  tags:
  - undocker
  - never

- name: Install RDP
  dnf:
    name: "{{item}}"
    state: absent 
    update_cache: yes
  loop:
     - xfce4
     - teamviewer
  tags:
  - inrdp
  - never

- name: Install MC
  dnf:
    name: "{{item}}"
    state: latest
    update_cache: yes
  loop:
     - mc
  tags:
  - inmc
  - never
 
- name: Install MC
  dnf:
    name: "{{item}}"
    state: absent
    update_cache: yes
  loop:
     - mc
  tags:
  - unmc
  - never
  
